#! /bin/sh
# /etc/init.d/tempnet-remote

## BEGIN INIT INFO
# Provides:		tempnet-remote
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Script to start tempnet-remote at boot
# Description:		Script to start tempnet-remote at boot
### END INIT INFO

case "$1" in
	start)
		echo "Starting tempnet-remote"
		screen -d -m python /srv/remote/tempnet_regd.py
		screen -d -m python /srv/remote/remoted.py
		;;
	stop)
		echo "Stopping tempnet-remote"
		killall -9 python
		;;
	*)
		echo "Usage: tempnet-remote  {start stop}"
		exit 1
		;;
esac

exit 0
